### ISSUE TITLE
Parens prevent removal of unused imports

### ISSUE THREAD

**Issue by chrisspen** [myint/autoflake#19] opened 2017-06-15 19:28 UTC
The use of parenthesis causes the `--remove-all-unused-imports` to miss unused imports.

e.g.

    $ echo -e "from os import path" > example.py
    $ cat example.py
    from os import path
    $ autoflake --in-place --remove-all-unused-imports example.py
    $ cat example.py
    $ echo -e "from os import (\npath\n)" > example.py
    $ cat example.py
    from os import (
    path
    )
    $ python example.py
    $ autoflake --in-place --remove-all-unused-imports example.py
    $ cat example.py
    from os import (
    path
    )

Since parens are legal import syntax, I would expect their presence of absence to have no effect on unused import checking.

**Comment by adhikasp** [comment] 2017-06-16 02:38
This was duplicate of https://github.com/myint/autoflake/issues/8. There was limitation on autoflake code to skip parentheses import.

**Closed** 2017-06-16 02:52 UTC
Labels: duplicate
