### ISSUE TITLE
Remove of multiline imports doesn't work properly

### ISSUE THREAD

**Issue by winklerrr** [myint/autoflake#17] opened 2017-05-18 10:43 UTC
The problem occurs when I try to remove some unused imports from a multiline import like this one:

```
from argparse import (ArgumentParser,
                      ArgumentError,
                      ArgumentTypeError)
```

Even if none of the imports in the multiline import is used, autoflake doesn't remove anything.

**Comment by myint** [comment] 2017-05-18 13:19
I think this is a duplicate of #8. autoflake currently doesn't support this yet.

**Closed by myint** 2017-05-18 13:19 UTC

**Comment by winklerrr** [comment] 2017-05-18 13:46
Oh yeah, you are right! Sorry, didn't see that one.
Will you implement a solution for that?

**Comment by myint** [comment] 2017-05-18 14:51
No problem.

I personally don't use import-from syntax. I usually just import the [module/package](https://github.com/myint/autoflake/blob/master/autoflake.py#L40). But if someone else provides a patch, I would be happy to merge it in.
